---
app:
  name: Hub
  class_name: Hub
  tagline: Ship faster
  description: Rails SaaS starter
design:
  primary_color: "#741a5c"
  secondary_color: "#43b690"
  accent_color: "#F59E0B"
  danger_color: "#EF4444"
  warning_color: "#F59E0B"
  info_color: "#3B82F6"
  success_color: "#ffffff"
  font_family: Inter
  heading_font_family: ''
  border_radius: 0.375rem
branding:
  logo_text: Hub
  footer_text:
  support_email: support@example.com
features:
  passwordless_auth: true
  stripe_payments: true
  admin_panel: true
seo:
  default_title_suffix:
  default_description:
  og_image: "/og-image.png"
products: []
