---
app_name: Hubby
app_class_name: Hub
tagline: Ship NOW, not tomorrow
description: Rails SaaS starter
logo_text: Hubby
footer_text: "© 2025 Hubby. All rights reserved."
support_email: hi@austn.net
primary_color: "#694f4f"
secondary_color: "#10B981"
accent_color: "#F59E0B"
danger_color: "#EF4444"
warning_color: "#F59E0B"
info_color: "#3B82F6"
success_color: "#10B981"
font_family: Inter
heading_font_family: Inter
border_radius: 0.375rem
passwordless_auth: true
stripe_payments: true
admin_panel: true
products: []
